routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/*
 * Logout routes
 */
Route::get('/logout','Auth\LoginController@logout')->name('logout');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');

/*
 * Logged in redirection
 */
Route::get('/home', 'HomeController@index')->name('home');

/*
 * Email verification routes
 */
Route::group([ 'prefix' => 'email', 'as' => 'verify.', 'middleware' => ['guest'] ], function () {
    Route::get('/verify/{sent?}', 'Auth\VerifyEmailController@form')->name('form');
    Route::post('/verify/', 'Auth\VerifyEmailController@resend')->name('resend');
    Route::get('/verify/token/{token}', 'Auth\VerifyEmailController@verify')->name('email');
});

/*
 * Guest ONLY Routes
 */
Route::group(['middleware' => ['guest'] ], function () {

    Route::get('/', 'FrontController@index')->name('front');

    Route::get('/unverified','Auth\LoginController@notVerified')->name('auth.unverified');
    Route::get('/inactive','Auth\LoginController@notActive')->name('auth.inactive');

    Route::get('login/{notice?}', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login')->name('auth.do-login');


// Registration Routes...
    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'Auth\RegisterController@register')->name('auth.do-register');

// Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');
});




/*
 * The Admin's Routes
 */

Route::group([ 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['admin'] ], function () {

    Route::get('/', 'Admin\DashboardController@index')->name('dashboard');

    Route::resource('objects', 'Admin\ObjectController');

    route::get('/roles/trash', 'Admin\RoleController@trash')->name('roles.trash');
    route::get('/roles/{id}/restore', 'Admin\RoleController@restore')->name('roles.restore');
    route::get('/roles/{id}/erase', 'Admin\RoleController@erase')->name('roles.erase');
    Route::resource('roles', 'Admin\RoleController');

});

Route::get('/void', 'Void\HomeController@index')->name('void');

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Builder;

class Role extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'flags', 'description'
    ];


    protected $casts = [
        'flags' => 'array',];


    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];


    /**
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'name';
    }


    /*
     * Accessors
     */

    /**
     * @return mixed
     */
    public function getAdminAttribute()
    {
        return $this->where('name', config('constants.roles.admin'))->first();
    }


    /*
     * Mutators
     */

    /**
     * @param $name
     */
    public function setNameAttribute($name)
    {
        $this->attributes['name'] = strtolower($name);
    }

    /*
     * Relations
     */

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function Users()
    {
        return $this->hasMany(User::class);
    }


    /*
     * Determinators :)
     */

    /**
     * @return bool
     */
    public function hasRelation(): bool
    {
        if ($this->users()->exists()) {
            return true;
        }

        return false;

    }

    /**
     * @param array $flags
     * @return bool
     */
    public function hasFlags(array $flags): bool
    {
        if (empty($this->flags)) {
            return false;
        }

        return in_array($flags, $this->flags);
    }

    /**
     * @param string $column
     * @param array $values
     * @return Builder
     */
    public function whereArrayHas(string $column, array $values) : Builder
    {
        $query = $this;
        foreach ($values as $value) {
            $query = $query->where($column, 'LIKE', '%\"'.$value.'\"%');
        }

        return $query;
    }


    /**
     * @param string $column
     * @param array $values
     * @return Builder
     */
    public function whereNotArrayHas(string $column, array $values) : Builder
    {
        $query = $this;
        foreach ($values as $value) {
            $query = $query->where($column, 'NOT LIKE', '%\"'.$value.'\"%');
        }

        return $query;
    }

}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\Role\CreateRoleRequest;
use App\Http\Requests\Role\UpdateRoleRequest;
use App\Models\Role;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Softon\SweetAlert\Facades\SWAL;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     * @param \App\Models\Role $role
     * @return \Illuminate\Http\Response
     */
    public function index(Role $role, Request $request)
    {
        return view('admin.roles.index')->with([
            'roles' => $role->all(),
            'user_id' => $request->user()->id,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.roles.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\Role\CreateRoleRequest $request
     * @param  \App\Models\Role $role
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRoleRequest $request, Role $role)
    {
        $created = $role->fill($request->all())->save();

        if (!$created) {
            return back()
                ->withErrors(['Create' => "Failed to create new Role in the database. Please check your database log for more information."])
                ->withInput();
        }

        SWAL::success("Created Role: {$role->name}!");

        return redirect(route('admin.roles.index'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Role $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        return view('admin.roles.edit', ['role' => $role]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \App\Http\Requests\Role\UpdateRoleRequest
     * @param \App\Models\Role $role
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRoleRequest $request, Role $role)
    {
        // If not keys not received from form, then it's mean to be emptied.

        $data = $request->all();
        $data = data_fill($data, 'flags', []);

        $updated = $role->update($data);

        if (!$updated) {
            return back()
                ->withErrors(['Create' => "Failed to update Role: {$role->name} in the database. Please check your database log for more information."])
                ->withInput();
        }

        SWAL::success("Updated Role: {$role->name}!");

        return redirect(route('admin.roles.index'));
    }

    /**
     * Remove the specified resource from storage.
     * @param Role $role
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Exception
     */
    public function destroy(Role $role)
    {
        if ($role->delete()) {
            SWAL::success("Deleted Role {$role->name}!");
            return redirect(route('admin.roles.index'));
        }

        SWAL::error("Failed to delete Role: {$role->name}.. Contact the admin");

        return back();
    }

    /**
     * @param Request $request
     * @param Role $role
     * @return $this
     */

    public function trash(Request $request, Role $role)
    {
        return view('admin.roles.trash')->with([
            'roles' => $role->onlyTrashed()->get(),
            'user_id' => $request->user()->id,
        ]);
    }


    /**
     * @param int $id
     * @param Role $role
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Exception
     */
    public function restore(string $name, Role $role)
    {

        $found = $role->onlyTrashed()->where('name', $name)->first();

        if (!empty($found)) {

            if ($restored = $role->onlyTrashed()->where('name', $name)->restore()) {

                SWAL::success("Restored Role {$found->name}!");
                return redirect(route('admin.roles.trash'));
            }

        }

        SWAL::error("Failed to restore Role: {$found->name}.. Contact the admin");
        return back();

    }

    /**
     * @param int $id
     * @param Role $role
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function erase(string $name, Role $role)
    {
        $found = $role->onlyTrashed()->where('name', $name)->first();

        if (!empty($found)) {


            if ($found->hasRelation()) {
                SWAL::warning("Unable to erased Role: {$found->name} because it's having relation with other object.");
                return back();
            }


            if ($erased = $role->onlyTrashed()->where('name', $name)->forceDelete()) {

                SWAL::success("Permanently erased Role {$found->name}!");
                return redirect(route('admin.roles.trash'));
            }

        }

        SWAL::error("Failed to erased Role: {$found->name}.. Contact the admin");
        return back();
    }


}

resources/views/admin/roles/create.blade.php
@extends('layouts.admin')
@section('title', 'Create Role - ')
@section('content')
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <i class="fa fa-user-plus"></i> Create New Role
            </h4>

            @if($errors->any())
                <div class="alert alert-danger small">
                    <h5>For your information:</h5>
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form method="POST" action="{{ route('admin.roles.store') }}"
                  class="form-horizontal {{ $errors->any() ? 'was-validated' : ''  }}">
                {{ csrf_field() }}

                <div class="form-group">
                    <label for="name">
                        Name
                    </label>

                    <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}"
                           required/>
                    <small>
                        Alphabets only. This will be saved in lowercase.
                    </small>
                </div>

                <div class="form-group">
                    <label for="description">
                        Description
                    </label>

                    <textarea id="description" type="text" class="form-control" name="description" >{{ old('description') }}</textarea>
                    <small>
                        This will shown to the user. Please explain this role.
                    </small>
                </div>

                <div class="form-group">
                    <label for="flags">
                        Flags
                    </label>
                    <div>
                        @foreach(config('constants.flags.role') as $flag)
                            <label>
                                <input name="flags[]" type="checkbox" value="{{ $flag }}"/> {{ $flag }}
                            </label>
                            <br />
                        @endforeach
                    </div>
                </div>

                <div class="form-group">
                    <button class="btn btn-primary">Create</button>
                </div>

            </form>
        </div>
    </div>
@endsection

@section('sidebar')
    @include('sidebars.admin')
@endsection

@section('footer')
    @include('components.footer')
@endsection

resources/views/admin/roles/edit.blade.php
@extends('layouts.admin')
@section('title', 'Edit Role - ')
@section('content')
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <i class="fa fa-user-plus"></i> Edit Role {{ $role->name }}
            </h4>

            @if($errors->any())
                <div class="alert alert-danger small">
                    <h5>For your information:</h5>
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form method="POST" action="{{ route('admin.roles.update', ['role' => $role]) }}"
                  class="form-horizontal {{ $errors->any() ? 'was-validated' : ''  }}">
                {{ csrf_field() }}

                {{ method_field('PUT') }}

                <div class="form-group">
                    <label for="name">
                        Name
                    </label>

                    <input id="name" type="text" class="form-control" name="name" value="{{ old('name') ?: $role->name }}"
                           required/>
                    <small>
                        Alphabets only. This will be saved in lowercase.
                    </small>
                </div>

                <div class="form-group">
                    <label for="description">
                        Description
                    </label>

                    <textarea id="description" type="text" class="form-control" name="description" >{{ old('description') ?: $role->description }}</textarea>
                    <small>
                        This will shown to the user. Please explain this role.
                    </small>
                </div>

                <div class="form-group">
                    <label for="flags">
                        Flags
                    </label>
                    <div>
                        @foreach(config('constants.flags.role') as $flag)
                            <label>
                                <input name="flags[]" type="checkbox" value="{{ $flag }}"
                                        {{ in_array($flag, (!empty(old('flags')) ? old('flags') : $role->flags)) ? 'checked' : '' }} /> {{ $flag }}
                            </label>
                            <br/>
                        @endforeach
                    </div>
                </div>

                <div class="form-group">
                    <button class="btn btn-primary">Save</button> <a href="{{ route('admin.roles.index') }}" class="btn btn-secondary">Back</a>
                </div>

            </form>
        </div>
    </div>
@endsection

@section('sidebar')
    @include('sidebars.admin')
@endsection

@section('footer')
    @include('components.footer')
@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.admin')
@section('title', 'Roles - ')
@section('content')
    <h4>
        <i class="fa fa-users"></i> Manage Roles
    </h4>
    <p class="text-justified text-secondary">
        Role used for categorising registered users, and for managing their object ownerships and authorisation.
    </p>
    <p>
        <a class="btn btn-sm btn-primary" href="{{ route('admin.roles.create') }}">
            Add New Role
        </a>
    </p>

    <table class="table table-info table-light table-striped">
        <thead>
        <tr>
            <th>
                #
            </th>
            <th>
                Roles
            </th>
            <th>
                Flags
            </th>
            <th>
                Actions
            </th>
        </tr>
        </thead>
        <tbody>
        @forelse($roles as $role)
            <tr>
                <td>
                    {{ $loop->iteration }}
                </td>
                <td>
                    {{ $role->name }}
                </td>
                <td>
                    @each('components.badge', $role->flags, 'badge')
                </td>
                <td>
                    @unless($role->name === 'admin')

                        <a href="{{ route('admin.roles.edit', ['role' => $role]) }}" class="badge">
                            <i class="fa fa-pencil"></i>
                            <span class="d-none d-md-inline">Edit</span>
                        </a>
                        <form class="inline" action="{{ route('admin.roles.destroy', [ 'role' => $role ]) }}"
                              method="POST">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <button class="btn btn-link badge text-danger">
                                <i class="fa fa-times"></i>
                                <span class="d-none d-md-inline">Delete</span>
                            </button>
                        </form>
                    @endunless
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="4" class="text-center text-muted">
                    There is no Role at the moment. Let's <a href="{{ route('admin.roles.create') }}">create a new
                        role</a> now! <i class="fa fa-smile-o"></i>
                </td>
            </tr>
        @endforelse
        </tbody>
    </table>
    <a class="text-danger" href="{{ route('admin.roles.trash') }}"><i class="fa fa-trash"></i> View Trash (Roles)</a>
@endsection

@section('sidebar')
    @include('sidebars.admin')
@endsection

@section('footer')
    @include('components.footer')
@endsection

resources/views/admin/roles/trash.blade.php
@extends('layouts.admin')
@section('title', 'Trash (Roles) - ')
@section('content')
    <h4 class="text-danger">
        <i class="fa fa-trash"></i> Trash (Roles)
    </h4>
    <p class="text-justified text-secondary">
        Deleted Roles.
    </p>
    <p class="text-right">
        <a class="btn btn-sm btn-danger" href="{{ route('admin.roles.create') }}">
            Empty Trash
        </a>
    </p>

    <table class="table table-info table-light table-striped">
        <thead class="bg-warning">
        <tr>
            <th>
                #
            </th>
            <th>
                Roles
            </th>
            <th>
                Flags
            </th>
            <th>
                Actions
            </th>
        </tr>
        </thead>
        <tbody>
        @forelse($roles as $role)
            <tr>
                <td>
                    {{ $loop->iteration }}
                </td>
                <td>
                    {{ $role->name }}
                </td>
                <td>
                    @each('components.badge', $role->flags, 'badge')
                </td>
                <td>

                    <a href="{{ route('admin.roles.restore', ['role' => $role->name]) }}" class="badge">
                        <i class="fa
                            fa-mail-reply"></i>
                        <span class="d-none d-md-inline">Restore</span>
                    </a>
                    <a href="{{ route('admin.roles.erase', ['role' => $role->name]) }}" class="badge text-danger">
                        <i class="fa
                            fa-bomb"></i>
                        <span class="d-none d-md-inline">Erase</span>
                    </a>
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="4" class="text-center text-muted">
                    There is no Role in the trash at the moment. <i class="fa fa-smile-o"></i>
                </td>
            </tr>
        @endforelse
        </tbody>
    </table>
@endsection

@section('sidebar')
    @include('sidebars.admin')
@endsection

@section('footer')
    @include('components.footer')
@endsection